# Generated by Django 5.2.4 on 2025-08-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_merge_20250826_1651"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartorder",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                    ("return_requested", "Return Requested"),
                    ("return_approved", "Return Approved"),
                    ("return_rejected", "Return Rejected"),
                    ("returned", "Returned"),
                    ("return_completed", "Return Completed"),
                ],
                default="processing",
                max_length=50,
            ),
        ),
    ]
